# Generated by Django 4.2.2 on 2023-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0002_department_doctorreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='availabledays',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorreg',
            name='timefrom',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctorreg',
            name='timeto',
            field=models.TimeField(null=True),
        ),
    ]
