# Generated by Django 4.2.2 on 2023-07-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0004_userreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_app.doctorreg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_app.userreg')),
            ],
        ),
    ]
