# Generated by Django 4.2.2 on 2023-07-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slottime',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
