# Generated by Django 4.2.2 on 2023-07-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0006_appointment_slottime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slotdate',
            field=models.DateField(null=True),
        ),
    ]
