# Generated by Django 4.2.2 on 2023-07-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0007_appointment_slotdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='slotdate',
        ),
    ]
