# Generated by Django 4.2.2 on 2023-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0008_remove_appointment_slotdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(default='Booked', max_length=30),
        ),
    ]
