# Generated by Django 4.2.2 on 2023-07-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0009_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
