# Generated by Django 4.2.2 on 2023-07-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0010_appointment_booked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booked_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
