# Generated by Django 4.2.2 on 2023-07-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='feedback_status',
            field=models.CharField(default='Empty', max_length=30),
        ),
    ]
